# Default settings for the application

# Context Window Size
DEFAULT_CONTEXT_WINDOW_SIZE = 2
MIN_CONTEXT_WINDOW_SIZE = 0
MAX_CONTEXT_WINDOW_SIZE = 5

# Temperature
DEFAULT_TEMPERATURE = 0.3
MIN_TEMPERATURE = 0.1
MAX_TEMPERATURE = 1.0

# Document Type
DEFAULT_DOCUMENT_TYPE = "Legal"

# Model
DEFAULT_MODEL = "gpt-4o-mini"

# Language Variant
DEFAULT_LANGUAGE_VARIANT = "British English"

# Rate Limiting
DEFAULT_RATE_LIMIT=450
DEFAULT_RATE_PERIOD=60

# Retry Settings
DEFAULT_MAX_RETRIES = 5
DEFAULT_BACKOFF_FACTOR = 2

# Token Limits
DEFAULT_TOKEN_LIMIT = 10000
DEFAULT_GPT35_TOKEN_LIMIT = 20000
DEFAULT_GPT4_TOKEN_LIMIT = 30000
